import {PaperId} from "../state";
import queryString from "querystring";

export function createFeedbackLink(
  paperId?: PaperId | undefined,
  extraContext?: object
) {
  /*
   * The URL and field ids below are generated by Google. The identifiers
   * are opaque to us, which means they could change (say, if we modify
   * the assocaited form). If this proves to be an issue we'll have to think
   * through alternative feedback mechanisms.
   */
  const baseUrl = "https://forms.gle/BvGeHYzUA1pHzcAK6";
  const params = {
    "entry.331961046": JSON.stringify(
      Object.assign({}, extraContext || {}, { paperId })
    ),
  };
  return `${baseUrl}?${queryString.stringify(params)}`;
}

export function openFeedbackWindow(url: string) {
  window.open(url, "scholar-reader-feedback", "width=640,height=829");
}

