FROM node:12.20.0 as build
WORKDIR /ui

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy over the source code and build
COPY . .
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV:-production}
RUN npm run build