FROM python:3.8.12


# Setup a spot for the api code
WORKDIR /api


# Install Python dependencies
RUN pip install --upgrade pip setuptools wheel
RUN pip install fastapi uvicorn httpx pydantic

########## COPYING SOURCE CODE FROM HERE ON ##########

# Copy over the source code
COPY main.py main.py

# Kick things off
ENTRYPOINT [ "uvicorn" ]
CMD ["main:app", "--host", "0.0.0.0", '--port', '3000']