FROM soldni/mmda-pytorch-transformer-cpu:1.2

# Setup a spot for the api code
WORKDIR /api

# Install Python dependencies
RUN pip install --upgrade pip install fastapi uvicorn httpx pydantic setuptools wheel

COPY pdod /tmp/pdod
# RUN pip install /tmp/pdod

########## COPYING SOURCE CODE FROM HERE ON ##########

# Copy over the source code
COPY main.py main.py

# Kick things off
ENTRYPOINT [ "uvicorn" ]
CMD ["main:app", "--host", "0.0.0.0", '--port', '3000']