FROM soldni/mmda-pytorch-transformer-cpu:1.2

# Setup a spot for the api code
WORKDIR /api

# Install Python dependencies
RUN pip install --upgrade pip install fastapi uvicorn httpx pydantic setuptools wheel

COPY pdod/ pdod/
# needs to be installed before requirements cuz it's needed for build
RUN pip install torch==1.9.0
RUN pip install -r pdod/requirements.txt

########## COPYING SOURCE CODE FROM HERE ON ##########

# Copy over the source code
COPY main.py main.py
COPY __init__.py __init__.py
ENV PYTHONPATH "/api/pdod/src/:${PYTHONPATH}"

# Kick things off
ENTRYPOINT [ "uvicorn" ]
CMD ["main:app", "--host", "0.0.0.0", '--port', '3000']